-- public.chatgroups definition

-- Drop table

-- DROP TABLE public.chatgroups;

CREATE TABLE public.chatgroups (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ch_name varchar NOT NULL,
	CONSTRAINT chatgroups_pk PRIMARY KEY (id),
	CONSTRAINT chatgroups_uk UNIQUE (ch_name)
);